name: hugo-site

type: golang:1.16

build:
    flavor: none

applications:
    app:
        type: golang:1.16
        hooks:
            build: |
                curl -sSOL https://github.com/gohugoio/hugo/releases/download/v0.121.1/hugo_extended_0.121.1_linux-amd64.deb
                dpkg -i hugo_extended_0.121.1_linux-amd64.deb
                hugo --destination=public
        web:
            locations:
                /:
                    root: public
                    index:
                        - index.html
                    expires: 1h
                    scripts: false
                    allow: true

routes:
    "https://{default}/":
        type: upstream
        upstream: "app:http"